function NRMSE_Results_Catch = f_nrmse_compute_catchME(Muscle_Param_Value, Compute_Param)

    % 
    % f_nrmse_compute_catchME: Fetch errors generated by execution "f_nrmse_compute" and initialize the NRMSE results 
    %
    % Args:
    %   Muscle_Param_Value: Muscle parameter values of the model to be calculated (Details are in "f_nrmse_compute")
    %   Compute_Param: Structure containing several structure of calculation parameters (Details are in "f_nrmse_compute")
    %
    % Return:
    %   NRMSE_Results_Catch: Structure containing i motion information and results  (Details are in "f_nrmse_compute")
    %
    % Authors: Yi-Hsuan Lin, System Optimization Laboratory, Department of Mechanical Engineering, National Taiwan University
    %

    % initialize
    penalty = nan;
    for i = 1 : Compute_Param.mot_num
        NRMSE_Results_Catch.mot(i).nrmse_value = penalty;
        NRMSE_Results_Catch.mot(i).nrmse_speed = penalty;
    end

    % try "f_nrmse_compute" or catch error
    try
        NRMSE_Results_Catch = f_nrmse_compute(Muscle_Param_Value, Compute_Param);
    catch ME
        if  (strcmp(ME.identifier,'MyComponent:ExistNaN'))
        elseif  (strcmp(ME.identifier,'MyComponent:NotFinish'))
        else
            throw(ME);
        end
    end
end